### ISSUE TITLE
Capstone Set-up issue

### ISSUE THREAD

**Issue by Spidey-Acer** [Peter-Kibet/module-2-capstone#1]
Dear Reviewer,

I wanted to provide you with an update on our team's progress and readiness to complete the capstone project. Please find the relevant information in the [Kaban project link](https://github.com/Peter-Kibet/module-2-capstone/projects/1).

I regret to inform you that my teammate was repeating the week. However, I am pleased to share that their appeal request was approved, allowing them to proceed to the next module. Consequently, I have been working on the project independently while awaiting a new partner. Unfortunately, the process of being paired again has taken longer than expected, prompting me to initiate work on the project on my own.

Thank you for your attention and please advise on how to proceed since I have never faced a challenge like this before.

**Comment by addod19** [comment]
### Hi @Peter-Kibet, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the project is a collaborative one done solo

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by shella12** [comment]
> 

I would suggest reaching out to student success, they will probably pair you with another partner by tomorrow. Meanwhile you can start working on your part of project and your new partner can pick up on his part once he/she is paired.

**Comment by shella12** [comment]
Hi @Peter-Kibet, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

- [ ] is not setup using the provided template
- [ ] Doesn't have the tasks assigned to team

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
